### ISSUE TITLE
css字体配置不正确

### ISSUE THREAD

**Issue by justinchuby** [tufu9441/maupassant-hexo#135]
随意打开一篇文章用chrome检查，可以看到font-family是
```css
.pure-g [class *="pure-u"] {
    font-family: sans-serif;
}
```
从`pure-u-1 pure-u-md-3-4`继承而来，而本来的字体
```css
font-family: "TIBch", "Classic Grotesque W01", "Helvetica Neue", Arial, "Hiragino Sans GB", "STHeiti", "Microsoft YaHei", "WenQuanYi Micro Hei", SimSun, sans-serif;
```
被覆盖了。

一个明显的后果是在一些（windows）系统下，英文文章的标点符号，如`‘`、`“`等会全角显示，不大美观。

一个解决办法是在`post-content`增加`font-family`的配置，或者有其他更好的办法？

**Comment by tufu9441** [comment]
这个我还真没注意过……你看看其它平台的这个主题会不会有同样的情况？如：http://chopstack.com/

**Comment by justinchuby** [comment]
我刚刚看情况是一样的：

<img width="322" alt="1" src="https://cloud.githubusercontent.com/assets/11205048/17055895/e12f0430-4fdd-11e6-81bc-89bccc542caf.png">
<img width="325" alt="2" src="https://cloud.githubusercontent.com/assets/11205048/17055898/e41bda92-4fdd-11e6-90e6-8f0c28d3008e.png">

应该就是使浏览器调用了默认的非衬线字体吧？

**Comment by tufu9441** [comment]
嗯，应该是，要不就按你说的思路改动一下吧……

**Comment by justinchuby** [comment]
根据pure css的说明 http://purecss.io/grids/#using-grids-with-custom-fonts，

> Using Grids with Your Font-Family
> 
> Pure Grids use a specific font stack to ensure the greatest OS/browser compatibility, and by default grid units will have font-family: sans-serif; applied — this is the default font stack Pure's Base (Normalize.css) applies to \<html\>, \<button\>, \<input\>, \<select\>, and \<textarea\> elements. Fortunately, it's quite easy to make sure your project's font stack applies to all content when using Pure. Instead of applying your font-family to only the <body> element, apply it like this:

```html
<style>
/*
When setting the primary font stack, apply it to the Pure grid units along
with `html`, `button`, `input`, `select`, and `textarea`. Pure Grids use
specific font stacks to ensure the greatest OS/browser compatibility.
*/
html, button, input, select, textarea,
.pure-g [class *= "pure-u"] {
    /* Set your content font stack here: */
    font-family: Georgia, Times, "Times New Roman", serif;
}
</style>
```

所以另一个办法是在style.scss里增加
```css
/*
pure css setting
When setting the primary font stack, apply it to the Pure grid units along
with `html`, `button`, `input`, `select`, and `textarea`. Pure Grids use
specific font stacks to ensure the greatest OS/browser compatibility.
*/
html, button, input, select, textarea,
.pure-g [class *= "pure-u"] {
    /* Set your content font stack here: */
    font-family: "PingFangSC-Regular", Helvetica, "Helvetica Neue", "Segoe UI", 
                 "Hiragino Sans GB", "Source Han Sans CN", "Microsoft YaHei", "STHeiti", "WenQuanYi Micro Hei", sans-serif;
}
```
并且把base.jade的
```jade
link(rel='stylesheet', type='text/css', href=url_for(theme.css) + '/style.css' + '?v=' + theme.version)
```
这一行放到
```jade
    link(rel='stylesheet', type='text/css', href='//cdn.bootcss.com/normalize/4.2.0/normalize.min.css')
    link(rel='stylesheet', type='text/css', href='//cdn.bootcss.com/pure/0.6.0/pure-min.css')
    link(rel='stylesheet', type='text/css', href='//cdn.bootcss.com/pure/0.6.0/grids-responsive-min.css')
```
之后。
