### ISSUE TITLE
pre_page属性会同时影响到archives中的个数

### ISSUE THREAD

**Issue by zysidea** [tufu9441/maupassant-hexo#181]

**Comment by tufu9441** [comment]
抱歉不太明白，能说清楚一点吗？

**Comment by zysidea** [comment]
比如说我想让主页显示5篇文章，那么pre_page是5，但是在归档里面也只显示了5条文章记录

**Comment by tufu9441** [comment]
控制归档页面显示的文章数需要安装`hexo-generator-archive`,然后在Hexo根目录的`_config.yml`文件中设置：
```YAML
archive_generator:
    per_page: 0 ##归档页面默认10篇文章标题
    yearly: true  ##生成年视图
    monthly: false ##生成月视图
```
