### ISSUE TITLE
关于归档分页

### ISSUE THREAD

**Issue by iiiyu** [tufu9441/maupassant-hexo#30]
我看到你的Blog Home 可以分页 而 归档没有分页. 我设置了_config.yml的 
per_page: 10
pagination_dir: page

好像就回连归档也分页 请问你的Blog怎么设置归档不分页的.

**Comment by alemonmk** [comment]
把以下一段
```yaml
per_page: 10
pagination_dir: page
```
換成
```yaml
pagination_dir: page
index_generator:
  per_page: 5
  order_by: -date

category_generator:
  per_page: 10

tag_generator:
  per_page: 10

archive_generator:
  per_page: 15
  yearly: true
  monthly: true
  daily: false
```
然後隨意改, 你的例子就是把 `archive_generator` 的 `per_page` 改成 0
