### ISSUE TITLE
头部导航菜单新增项无法切换

### ISSUE THREAD

**Issue by huluo666** [tufu9441/maupassant-hexo#359]
使用以下方式新增导航项，使用directory: /categories/customMenu方式无法切换tab
```
menu: 
  - page: home
    directory: .
  - page: archive
    directory: archives/
  - page: 随笔
    directory: /categories/essay
  - page: 阅读
    directory: /categories/read
```
预览 http://huluo666.cn/
