### ISSUE TITLE
代码高亮失效

### ISSUE THREAD

**Issue by michaelHL** [tufu9441/maupassant-hexo#371]
文章中的代码块高亮如下（以yaml为例）：

```yaml
title: Test Math
date: 2016-04-05 14:16:00
categories: math
mathjax: true
---
````

但是生成的结果是这样的：
![](https://i.imgur.com/pP0dqaf.png)

颜色显然不像[文档](https://www.haomwei.com/technology/maupassant-hexo.html#%E8%AF%AD%E6%B3%95%E9%AB%98%E4%BA%AE)中那样。Hexo版本如下：
```bash
$ hexo -v
hexo: 3.7.0
hexo-cli: 1.1.0
os: Windows_NT 10.0.16299 win32 x64
http_parser: 2.7.0
node: 8.9.0
v8: 6.1.534.46
```
