### ISSUE TITLE
关于代码框样式

### ISSUE THREAD

**Issue by weearc** [tufu9441/maupassant-hexo#447]
可否将code-blocks的inline-height属性去除？添加该属性以后非常影响美观度

**Comment by weearc** [comment]
```CSS
/* syntax highlight customized*/

figure.highlight,
.codeblock {
    background: #f7f8f8;
    margin: 0px 0;
    color: #333;
    padding-bottom: 0;
}

figure.highlight table,
.codeblock table {
    display: block;
    width: 100%;
}

figure.highlight pre,
figure.highlight .gutter,
figure.highlight .code,
figure.highlight .tag,
.codeblock pre,
.codeblock .gutter,
.codeblock .code,
.codeblock .tag {
    background-color: inherit;
    font-family: Menlo, Consolas, monospace;
    border: none;
    padding: 0;
    margin: 0;
    cursor: text;
}

figure.highlight .gutter,
figure.highlight .code,
.codeblock .gutter,
.codeblock .code {
    vertical-align: none;
}

figure.highlight.plain .gutter,
.codeblock.plain .gutter {
    display: none;
}

figure.highlight figcaption,
.codeblock figcaption {
    font-size: 13px;
    padding: 0 15px 20px;
    margin: 0;
    background: #f7f8f8;
    color: #999999;
}

figure.highlight figcaption a,
.codeblock figcaption a {
    float: right;
    color: #00d042;
}

figure.highlight .gutter,
.codeblock .gutter {
    background: #efefef;
    padding-top: 0.3em;
    padding-bottom: 0.3em;
    padding-left: 15px;
    padding-right: 10px;
}

figure.highlight .code,
.codeblock .code {
    padding: 0.3em 15px 0.5em 1em;
    width: 100%;
}

figure.highlight .code pre,
.codeblock .code pre {
    max-width: 700px;
    overflow-x: auto;
    overflow-y: hidden;
}

figure.highlight .line,
.codeblock .line {
    height: 1.3em;
    font-size: 13px;
}

//////////////////////////////////////////////////////////////////////
```

**Comment by tufu9441** [comment]
能否展示一下具体区别呀？

**Comment by weearc** [comment]
可通过自行更改pug文件实现。


 
---原始邮件---
发件人: "tufu9441"<notifications@github.com>
发送时间: 2019年4月20日 16:13:36
收件人: "tufu9441/maupassant-hexo"<maupassant-hexo@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"weearc"<q19981121@163.com>;
主题: Re: [tufu9441/maupassant-hexo] 关于代码框样式 (#447)



能否展示一下具体区别呀？

**Comment by weearc** [comment]
@tufu9441 不好意思刚刚回复错了…

**Comment by weearc** [comment]
更改效果可见[这里](https://blog.weearc.top/posts/6009.html)主要区别还是更改了行距，行号对齐以及配色

**Comment by tufu9441** [comment]
嗯嗯，我看到了你提交的PR，但是行号对齐的效果似乎并不好？
![Xnip2019-04-20_16-24-58](https://user-images.githubusercontent.com/6790361/56454811-e62e3200-6388-11e9-881e-b7f4efd5598c.jpg)

**Comment by weearc** [comment]
唔，确实是这样，看来还需要进一步调整

**Comment by weearc** [comment]
再一次做了修改，将**vertical-align** 属性修改了一下：
```CSS
figure.highlight,
.codeblock {
    background: #f7f8f8;
    margin: 0px 0;
    color: #333;
    padding-bottom: 0;
}

figure.highlight table,
.codeblock table {
    display: block;
    width: 100%;
}

figure.highlight pre,
figure.highlight .gutter,
figure.highlight .code,
figure.highlight .tag,
.codeblock pre,
.codeblock .gutter,
.codeblock .code,
.codeblock .tag {
    background-color: inherit;
    font-family: Menlo, Consolas, monospace;
    border: none;
    padding: 0;
    margin: 0;
    cursor: text;
}

figure.highlight .gutter,
figure.highlight .code,
.codeblock .gutter,
.codeblock .code {
    vertical-align: super;
}

figure.highlight.plain .gutter,
.codeblock.plain .gutter {
    display: none;
}

figure.highlight figcaption,
.codeblock figcaption {
    font-size: 13px;
    padding: 0 15px 20px;
    margin: 0;
    background: #f7f8f8;
    color: #999999;
}

figure.highlight figcaption a,
.codeblock figcaption a {
    float: right;
    color: #00d042;
}

figure.highlight .gutter,
.codeblock .gutter {
    background: #efefef;
    padding-top: 0;
    padding-bottom: 0;
    padding-left: 15px;
    padding-right: 10px;
    text-align: right;
}

figure.highlight .code,
.codeblock .code {
    padding: 2vh 15px 2vh 1em;
    width: 100%;
}

figure.highlight .code pre,
.codeblock .code pre {
    max-width: 700px;
    overflow-x: auto;
    overflow-y: hidden;
}

figure.highlight .line,
.codeblock .line {
    height: 1.3em;
    font-size: 13px;
}
```
效果如下：[链接](http://blog.weearc.top/posts/6009.html#添加点击的烟花效果)
