### ISSUE TITLE
config.title 中的特殊符號導致 DisqusJS 報錯無法顯示

### ISSUE THREAD

**Issue by AkazaRenn** [tufu9441/maupassant-hexo#503]
```yaml
disqus:
  enable: true ## If you want to use Disqus comment system, please set the value to true.
  shortname: **** ## Your disqus_shortname, e.g. username
  api: https://disqus.com/api/ ## You can visit Disqus comments in China mainland without barriers using Disqus API, e.g. https://disqus.skk.moe/disqus/
  apikey: **** ## Your API key obtained in Disqus API Application, e.g. yk00ZB1fjYGRkrCrDDRYDUjpp26GJWJiJRZQZ5SY0r3th5FMW6pnSzQMnWH7ua7r
  admin: akaza_renn ## Username of your Disqus moderator, e.g. username
  admin_label: Mod ## The text of Disqus moderator badge, e.g. Mod
```
這是 `_config.yml` 關於 Disqus 的内容，但是部署之後任意頁面沒有 Disqus 評論部件展示，參見 https://renn.engineer/about/
