### ISSUE TITLE
请问首页的about界面如何设置？

### ISSUE THREAD

**Issue by TheLittleJimmy** [tufu9441/maupassant-hexo#525]
我是hexo小白，感谢作者的精美模板！请问我该如何设置首页的about me呢，在帮助文档没找到。

**Comment by 0x2CA** [comment]
你在主题配置，菜单选项加入关于就好。
类似:
```
menu:
  - page: home
    directory: .
    icon: fa-home
  - page: archive
    directory: archives/
    icon: fa-archive
  - page: about
    directory: about/
    icon: fa-user
```
